baseURL = '/'
languageCode = 'en-us'
defaultContentLanguage = "en"
title = 'The Kellude'
theme = 'spectral'

googleAnalytics = "G-B2H5W1LCHG"

[params]
fancyTitle = "Kellude"
copyright = "The Kellude"
description = "The Kellude specializes in software development, <br />data collection, processing, analytics, and architecture.<br /> We deliver innovative solutions to help businesses <br /> harness data and make informed decisions."
body_is_markdown = true

[params.one]
enable = true
title = 'Custom Solutions, Tailored for Your Success'
body = '''
We create custom software, data management, analytics, and architecture solutions tailored to your unique needs.
Our goal is to deliver innovative, scalable technology that drives your success.
'''

[[params.one.icon]]
icon = "solid fa-code"
style = "1"
label = "Code"

[[params.one.icon]]
icon = "solid fa-cloud"
style = "2"
label = "Cloud"

[[params.one.icon]]
icon = "solid fa-database"
style = "3"
label = "Ipsum"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
img_alt = "blurry background: white/grey"
title = 'Smarter Data, Better Decisions'
body = 'Turn your data into actionable insights with our advanced analytics and data management solutions. We help you harness the power of your information to make informed, strategic decisions with confidence.'

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Scalable Systems for Growth'
body = 'We design and build robust software architectures that grow with your business. From start-ups to enterprises, our scalable solutions ensure your technology evolves as your needs expand.'

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Seamless Integration,<br /> Effortless Operations'
body = 'Streamline your workflows with custom integrations that connect your tools and systems. We make your technology work together seamlessly, saving time and improving efficiency.'

[params.three]
enable = true
title = 'Our Services'
body = '''
We offer a range of services to help you harness the power of technology and data. From custom software development to advanced analytics, we deliver innovative solutions that drive your success.
'''

[[params.three.feature]]
icon = "solid fa-code"
title = "Custom Software, Built for You"
body = "From intuitive apps to complex enterprise systems, we create software solutions designed to streamline your operations and elevate your business."

[[params.three.feature]]
icon = "solid fa-building-circle-check"
title = "Robust Data Architecture, Endless Possibilities"
body = "We design data frameworks that are scalable, efficient, and secure, ensuring your information is always accessible and organized for optimal performance."

[[params.three.feature]]
icon = "solid fa-chart-simple"
title = "Analytics That Drive Impact"
body = "Unlock the value hidden in your data. Our analytics solutions transform raw numbers into meaningful insights that guide smarter decision-making."

[[params.three.feature]]
icon = "brands fa-cloudflare"
title = "Cloud Solutions for Modern Businesses"
body = "Leverage the power of the cloud to improve scalability, reduce costs, and ensure reliable access. Our cloud computing expertise takes your operations to the next level."

[[params.three.feature]]
icon = "solid fa-gears"
title = "Smarter Automation, Greater Efficiency"
body = "Automate repetitive tasks and optimize your workflows with tailored automation solutions, giving your team more time to focus on what matters."

[[params.three.feature]]
icon = "solid fa-robot"
title = "Harness the Power of Generative AI"
body = "Revolutionize creativity and problem-solving with cutting-edge generative AI tools. We integrate AI-driven solutions to innovate and transform your processes."

[params.contact]
enable = true
title = "Contact"
body = "Have a project in mind or a challenge to solve? Reach out today, and let’s discuss how we can help you achieve your goals. Fill out the form below, and we’ll get back to you promptly to explore what we can do for you!"
subject = "New Kellude Contact Submission!"
formspree_form_id = "mgvezwpo"
